apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
  labels:
    app: phpldapadmin
  namespace: kube-auth
spec:
  ports:
    - port: 80
      name: phpldapadmin
      targetPort: 80
  selector:
    app: phpldapadmin
  type: NodePort

