apiVersion: v1
kind: Secret
metadata:
  name: openldap
  namespace: kube-auth
  labels:
    app: openldap
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: "bGRhcFBhNTV3b3Jk"
  LDAP_CONFIG_PASSWORD: "bGRhcGNvbmZpZ1BhNTV3b3Jk"
