apiVersion: v1
kind: Namespace
metadata:
  name: xen-projects
  labels:
    group: xen
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: xen
  namespace: xen-projects
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-xen-projects
  namespace: xen-projects
subjects:
- kind: Group
  name: xen
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: xen
  apiGroup: rbac.authorization.k8s.io
---

